import type { Metadata } from 'next';
import { QueryClientProviderWrapper } from '@/components/QueryClientProviderWrapper';
import { MantineProvider, mantineHtmlProps } from '@mantine/core';
import '@mantine/core/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
import './layout.css';

export const metadata: Metadata = {
  title: 'Port0',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body>
        <QueryClientProviderWrapper>
          <MantineProvider>{children}</MantineProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
